Update flutter-build.yml

diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -149,6 +149,16 @@ jobs:
         uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
         with:
           submodules: recursive
+      - name: Set custom server and key
+        shell: bash
+        run: |
+             sed -i 's|"rs-ny.rustdesk.com"|"${{ secrets.RENDEZVOUS_SERVER }}"|' libs/hbb_common/src/config.rs
+             sed -i 's|"OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw="|"${{ secrets.RS_PUB_KEY }}"|' libs/hbb_common/src/config.rs
+             grep -nE 'pub const (RENDEZVOUS_SERVERS|RS_PUB_KEY)' libs/hbb_common/src/config.rs
+             if grep -qE 'rs-ny\.rustdesk\.com|OeVuKk5nlHiXp' libs/hbb_common/src/config.rs; then
+               echo "::error::Patch nicht angewendet"
+               exit 1
+             fi
 
       - name: Restore bridge files
         uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
